// vueJS/src/@core/presentation/shared/TitleView.vue
<script setup lang="ts">
const props = defineProps({
  title: { type: String }
})
</script>

<template>
  <div class="flex items-center p-2">
    <span class="mr-auto text-gray-300 uppercase text-lg border-b-4 border-b-red-600">
      {{ props.title }}
    </span>
    <slot name="actions" />
  </div>
</template>

// reactJS/src/@core/presentation/shared/TitleView.tsx
import React, { ReactNode } from 'react'

const TitleView = ({ action, title }: { action?: ReactNode, title: string }) => {
  return (
    <div className="flex items-center p-2">
      <span className="mr-auto text-gray-300 uppercase text-lg border-b-4 border-b-red-600">
        {title}
      </span>

      {action}
    </div>
  )
}

export default TitleView
