// vueJS/src/@core/presentation/layout/LayoutDefault.vue
<script setup lang="ts">
// import { RouterLink, RouterView } from 'vue-router'
import Container from './components/Container.vue'
import Header from './components/Header.vue'
import Main from './components/Main.vue'
import Footer from './components/Footer.vue'

const title = 'vueJS'
</script>

<template>
  <Container>
    <Header :title="title" />

    <Main>
      <slot />
    </Main>

    <Footer />
  </Container>
</template>

<style scoped></style>

// reactJS/src/@core/presentation/layout/LayoutDefault.tsx
import React, { ReactNode } from 'react'

import Header from './components/Header'
import Main from './components/Main'
import Footer from './components/Footer'
import Container from './components/Container'

const LayoutDefault = ({ children }: { children: ReactNode }) => {
  const title = 'reactJS'

  return (
    <Container>
      <Header title={title} />

      <Main>
        {children}
      </Main>

      <Footer />
    </Container>
  )
}

export default LayoutDefault
