// vueJS/src/@core/presentation/views/MovieView/index.vue
<script setup lang="ts">
import { useRoute } from 'vue-router'
import { onMounted, reactive } from 'vue'
import type IMovie from '../../../domain/Movie'
import { movieController } from '../../../controllers/MovieController' //'../../..//controllers/MovieController' // using
import LayoutDefault from './../../layout/LayoutDefault.vue'
import MoviePoster from '../../shared/MoviePoster.vue'
import TitleView from '../../shared/TitleView.vue'
import Link from '../../shared/ui/Link.vue'

const route = useRoute()
const currentId = route.params.id

const movie = reactive<IMovie>({
  id: 0,
  backdropPath: '',
  originalLanguage: '',
  originalTitle: '',
  overview: '',
  posterPath: '',
  releaseDate: '',
  title: '',
  voteAverage: 0,
  voteCount: 0
})

async function getData() {
  const res = await movieController.getMovies(Number(currentId))

  movie.posterPath = res.data.posterPath
  movie.backdropPath = res.data.backdropPath
  movie.originalLanguage = res.data.originalLanguage
  movie.title = res.data.title
  movie.overview = res.data.overview
  movie.releaseDate = res.data.releaseDate
  movie.voteCount = res.data.voteCount
  movie.voteAverage = res.data.voteAverage
}

onMounted(() => {
  getData()
})
</script>

<template>
  <LayoutDefault>
    <TitleView title="Info" />
    <div class="sm:grid grid-cols-5 gap-4 py-4 min-h[240px]">
      <div class="sm:col-span-1 overflow-hidden">
        <MoviePoster v-if="movie.posterPath" :poster-path="movie.posterPath" class="h-full" />
      </div>
      <div class="sm:col-span-4 flex flex-col">
        <div class="text-gray-200 flex flex-col gap-2 mb-3">
          <p class="text-sm">Title: {{ movie.title }}</p>
          <p class="text-sm">Data: {{ movie.releaseDate }}</p>
          <p class="text-sm">Original language: {{ movie.originalLanguage }}</p>
        </div>

        <div class="mt-auto flex gap-2">
          <Link :to="movie.posterPath" :external="true" target="_blank">see poster</Link>
          <Link :to="movie.backdropPath" :external="true" target="_blank">see backdrop</Link>
        </div>
      </div>
    </div>

    <TitleView title="Sinopse" />
    <div class="relative bg-black/50 shadow-lg min-h-[485px]">
      <MoviePoster
        v-if="movie.posterPath"
        :poster-path="movie.backdropPath"
        class="h-full w-full object-cover object-center opacity-50"
      />
      <p
        class="absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] italic text-gray-200 p-4"
      >
        {{ movie.overview }}
      </p>
    </div>
  </LayoutDefault>
</template>

<style scoped></style>

// reactJS/src/@core/presentation/views/MovieView/index.tsx
import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import IMovie from '../../../domain/Movie'
import { movieController } from '../../../controllers/MovieController'
import LayoutDefault from './../../layout/LayoutDefault'
import MoviePoster from '../../shared/MoviePoster'
import TitleView from '../../shared/TitleView'
import Link from '../../shared/ui/Link'

const MovieView = () => {
  const params = useParams()
  const currentId = params.id

  const [movie, setMovie] = useState<IMovie>({
    id: 0,
    backdropPath: '',
    originalLanguage: '',
    originalTitle: '',
    overview: '',
    posterPath: '',
    releaseDate: '',
    title: '',
    voteAverage: 0,
    voteCount: 0
  })

  async function getData() {
    const res = await movieController.getMovies(Number(currentId))

    setMovie(prev => ({
      ...prev,
      posterPath: res.data.posterPath,
      backdropPath: res.data.backdropPath,
      originalLanguage: res.data.originalLanguage,
      title: res.data.title,
      overview: res.data.overview,
      releaseDate: res.data.releaseDate,
      voteCount: res.data.voteCount,
      voteAverage: res.data.voteAverage,
    }))
  }

  useEffect(() => {
    getData()
    // eslint-disable-next-line
  }, [])


  return (
    <LayoutDefault>
      <TitleView title="Info" />
      <div className="sm:grid grid-cols-5 gap-4 py-4 min-h[240px]">
        <div className="sm:col-span-1 overflow-hidden">
          {movie.posterPath && <MoviePoster posterPath={movie.posterPath} className="h-full" />}
        </div>
        <div className="sm:col-span-4 flex flex-col">
          <div className="text-gray-200 flex flex-col gap-2 mb-3">
            <p className="text-sm">Title: {movie.title}</p>
            <p className="text-sm">Data: {movie.releaseDate}</p>
            <p className="text-sm">Original language: {movie.originalLanguage}</p>
          </div>

          <div className="mt-auto flex gap-2">
            <Link to={movie.posterPath} external target="_blank">see poster</Link>
            <Link to={movie.backdropPath} external target="_blank">see backdrop</Link>
          </div>
        </div>
      </div>

      <TitleView title="Sinopse" />
      <div className="relative bg-black/50 shadow-lg min-h-[485px]">
        {movie.posterPath && (
          <MoviePoster
            posterPath={movie.backdropPath}
            className="h-full w-full object-cover object-center opacity-50"
          />
        )}
        <p
          className="absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] italic text-gray-200 p-4"
        >
          {movie.overview}
        </p>
      </div>
    </LayoutDefault>
  )
}

export default MovieView
